### ISSUE TITLE
Reset password is not working

### ISSUE THREAD

**Issue by raamb** [singnet/refactored-dapp#133]
Resetting a password is sending a verification code but its not clear where the code has to be entered.

**Comment by Vivek205** [comment]
sure. fixed the forgot password flow.. replaced email sent text with a click here text where user can click to get into otp section..

**Comment by Vivek205** [comment]
Made changes in https://github.com/Vivek205/refactored-dapp/pull/87. Waiting for the parent PR to be completed. https://github.com/Vivek205/refactored-dapp/pull/83
